version: '3.8'

services:
  php:
    image: php:7.4-apache
    container_name: my-php-app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html

  mongo:
    image: mongo
    container_name: my-mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example